name: "NowSecure Report Parser"
description: "Reformat the output from NowSecure in order to be used in the Jira Server Integration Action"
inputs:
  PLATFORMS:
    description: "An array of the platforms the NowSecure report has run against"
    required: true
  NOWSECURE_ACCESS_TOKEN:
    description: "The access token retrieved from NowSecure in order for the action to be able to interact with NowSecure's API"
    required: true
  # the following fields are exposed by default: key, title, description, recommendation, severity
  REPORT_FIELDS:
    description: "A list of valid fields from NowSecure's assessement report"
    required: false
    default: ""
  # at least one of the following needs to be included
  IOS_PACKAGE:
    description: "The name of the app's package for the iOS platform"
    required: false
  ANDROID_PACKAGE:
    description: "The name of the app's package for the Android platform"
    required: false
  NOWSECURE_GROUP_ID:
    description: "The application group to use for the assessment"
    required: true
  SEVERITY_LIST:
    description: "The list of severity issues provided by NowSecure"
    required: false
  EXTRACT_REPORT:
    description: "Retrieve the NowSecure report per platform, per assessment."
    required: false
    default: false
outputs:
  NOWSECURE_DATA:
    description: "JSON style object with specific data from the NowSecure report"
runs:
  using: "docker"
  image: "Dockerfile"
