name: Int Tests

on:
 push

jobs:
  int-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout Nowsecure GitHub Action Repo
        uses: actions/checkout@v2
        with:
         repository: camelotls/actions-nowsecure
         ref: v1.3.0
         token: ${{ secrets.MACHINEUSER_GITHUB_TOKEN }}
         path: actions-nowsecure

      - name: Execute Nowsecure action
        id: nowsecure_action
        uses: ./actions-nowsecure/
        with:
          PLATFORMS: 'ios,android'
          NOWSECURE_ACCESS_TOKEN: ${{ secrets.NOWSECURE_ACCESS_TOKEN }}
          IOS_PACKAGE: 'co.uk.camelot'
          ANDROID_PACKAGE: 'uk.co.theofficialnationallotteryapp.android.play'
          NOWSECURE_GROUP_ID: ${{ secrets.UK_NOWSECURE_GROUP_ID }}
          SEVERITY_LIST: 'high,medium,low'
      - name: Run Int Tests
        uses: ./.github/actions/schema-validator
        with:
          MACHINEUSER_GITHUB_TOKEN: ${{ secrets.MACHINEUSER_GITHUB_TOKEN }}
          INPUT_DATA: ${{ steps.nowsecure_action.outputs.nowsecureReportData }}
